#!/usr/bin/env bash

PROJ="$(basename "$(pwd)")"
NAME="open-code-${PROJ}"
ENV_FILE="$HOME/.config/opencode/credentials.env"
ENV_FILE_ARGS=()

if [ -f "$ENV_FILE" ]; then
  ENV_FILE_ARGS=(--env-file "$ENV_FILE")
fi

exec docker run --rm --tty --interactive \
  --name "$NAME" \
  --add-host=host.docker.internal:host-gateway \
  "${ENV_FILE_ARGS[@]}" \
  -e AWS_PAGER="" \
  -e GH_PAGER=cat \
  -v "$HOME/.aws:/home/agent/.aws" \
  -v "$HOME/.kube:/home/agent/.kube" \
  -v "$HOME/.local/state/opencode:/home/agent/.local/state/opencode" \
  -v "$HOME/.local/share/opencode:/home/agent/.local/share/opencode" \
  -v "$HOME/.config/gh:/home/agent/.config/gh" \
  -v "$HOME/.config/opencode:/home/agent/.config/opencode" \
  -v "$(pwd):/app:rw" \
  open-code "$@"
